name: Deploy as static page

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: "deploy"
  cancel-in-progress: false

jobs:
  build-deploy:
    if: github.actor != 'dependabot[bot]'
    environment:
      name: deploy
      url: ${{ vars.DEPLOY_URL }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "npm"
      - name: Use corepack
        run: corepack enable
      - name: Install node dependencies
        run: yarn
      - name: Build project
        env:
          VITE_ROOM_MANAGER_URL: ${{ secrets.ROOM_MANAGER_URL }}
        run: yarn build
      - name: Copy files to deployment server
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          rm: true
          strip_components: 1
          source: dist/*
          target: /usr/share/nginx/html
